My Application: MousePicker Class Reference
MousePicker Class Reference
#include <MousePicker.h>
Public Member Functions
MousePicker ()
Default Constructor.
MousePicker (Camera camera, Mtx44 projection)
Constructor.
~MousePicker ()
Default Destructor.
Vector3 getCurrentRay ()
Gets the current ray and return it.
Vector3 calculateMouseRay ()
Calculate's the mouse ray from screen coordinates to world coordinates.
Vector3 WorldCoord ()
Calculates the coordinates on X and Z world space.
void update ()
Updates the class to the latest camera position, target, up and caluclate the latest mouse ray.
void set (Camera camera, Mtx44 projection)
Sets camera and projection.
Private Attributes
Vector3 currentRay
Mtx44 projection
Mtx44 view
Camera camera
float x
float y
Detailed Description
Definition at line 22 of file MousePicker.h.
Constructor & Destructor Documentation
MousePicker::MousePicker ()
Default Constructor.
Definition at line 23 of file MousePicker.cpp.
MousePicker::MousePicker (Camera camera, Mtx44 projection)
Constructor.
Parameters
camera Gets current camera to pass in to the class.
projection Gets the projection matrix to pass in to the class.
Definition at line 50 of file MousePicker.cpp.
References camera, Camera::position, projection, Mtx44::SetToLookAt(), Camera::target, Camera::up, view, Vector3::x, Vector3::y, and Vector3::z.
MousePicker::~MousePicker ()
Default Destructor.
Definition at line 33 of file MousePicker.cpp.
Member Function Documentation
Vector3 MousePicker::calculateMouseRay ()
Calculate's the mouse ray from screen coordinates to world coordinates.
Returns
Returns a normalized Vector3
Definition at line 92 of file MousePicker.cpp.
References Mtx44::GetInverse(), Application::getMouse(), Vector3::Normalized(), projection, Application::screenHeight, Application::screenWidth, Vector3::Set(), view, Vector3::x, x, Vector3::y, y, and Vector3::z.
Referenced by update().
Vector3 MousePicker::getCurrentRay ()
Gets the current ray and return it.
Returns
Returns current ray
Definition at line 66 of file MousePicker.cpp.
References currentRay.
Referenced by SP2::MouseSelection().
void MousePicker::set (Camera camera, Mtx44 projection)
Sets camera and projection.
Parameters
camera Current Camera
projection projection matrix
Definition at line 148 of file MousePicker.cpp.
References camera, and projection.
Referenced by SP2::RTSUpdates().
void MousePicker::update ()
Updates the class to the latest camera position, target, up and caluclate the latest mouse ray.
Definition at line 77 of file MousePicker.cpp.
References calculateMouseRay(), camera, currentRay, Camera::position, Mtx44::SetToLookAt(), Camera::target, Camera::up, view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::RTSUpdates().
Vector3 MousePicker::WorldCoord ()
Calculates the coordinates on X and Z world space.
Returns
Returns a Vector3 without Y coordinates.
Definition at line 117 of file MousePicker.cpp.
References camera, currentRay, Vector3::Dot(), Camera::position, and Vector3::y.
Referenced by SP2::MouseSelection(), and SP2::RTSUpdates().
Field Documentation
Camera MousePicker::camera private
Definition at line 27 of file MousePicker.h.
Referenced by MousePicker(), set(), update(), and WorldCoord().
Vector3 MousePicker::currentRay private
Definition at line 25 of file MousePicker.h.
Referenced by getCurrentRay(), update(), and WorldCoord().
Mtx44 MousePicker::projection private
Definition at line 26 of file MousePicker.h.
Referenced by calculateMouseRay(), MousePicker(), and set().
Mtx44 MousePicker::view private
Definition at line 26 of file MousePicker.h.
Referenced by calculateMouseRay(), MousePicker(), and update().
float MousePicker::x private
Definition at line 28 of file MousePicker.h.
Referenced by calculateMouseRay().
float MousePicker::y private
Definition at line 28 of file MousePicker.h.
Referenced by calculateMouseRay().
The documentation for this class was generated from the following files:
Zyzrag/Source/MousePicker.h
Zyzrag/Source/MousePicker.cpp