My Application: sharedData Class Reference
sharedData Class Reference
#include <sharedData.h>
Public Member Functions
bool Delay (double time)
void DelayIncrement (double dt, double time=0.5f)
Static Public Member Functions
static sharedData * GetInstance ()
Data Fields
bool quit = false
Private Member Functions
sharedData ()
Private Attributes
float delay
Detailed Description
Definition at line 4 of file sharedData.h.
Constructor & Destructor Documentation
sharedData::sharedData () inline private
Definition at line 33 of file sharedData.h.
Member Function Documentation
bool sharedData::Delay (double time) inline
Definition at line 12 of file sharedData.h.
References delay.
Referenced by SP2::RTSUpdates().
void sharedData::DelayIncrement (double dt, double time = 0.5f) inline
Definition at line 22 of file sharedData.h.
References delay.
Referenced by SP2::Update().
static sharedData* sharedData::GetInstance () inline static
Definition at line 6 of file sharedData.h.
Referenced by SP2::gameOverUpdate(), SP2::generalUpdates(), SP2::inPlayerShipUpdates(), SP2::inSpaceStationUpdates(), SP2::mainMenuUpdates(), SP2::RTSUpdates(), Application::Run(), SP2::shopUpdates(), Camera::TPSMovement(), and SP2::Update().
Field Documentation
float sharedData::delay private
Definition at line 33 of file sharedData.h.
Referenced by Delay(), and DelayIncrement().
bool sharedData::quit = false
Definition at line 30 of file sharedData.h.
Referenced by SP2::gameOverUpdate(), and SP2::Update().
The documentation for this class was generated from the following file:
Zyzrag/Source/sharedData.h