My Application: Application Class Reference
Application Class Reference
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
void Run ()
void Exit ()
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
static void getMouse (double &x, double &y)
static void centerMouse ()
static void hideMouse ()
static void showMouse ()
Static Public Attributes
static int screenWidth = 0
static int screenHeight = 0
static double scrollX = 0
static double scrollY = 0
Private Attributes
StopWatch m_timer
Detailed Description
Definition at line 8 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 44 of file Application.cpp.
Application::~Application ()
Definition at line 48 of file Application.cpp.
Member Function Documentation
void Application::centerMouse () static
Definition at line 157 of file Application.cpp.
References m_window, screenHeight, and screenWidth.
Referenced by Camera::DisableCursor(), SP2::mainMenuUpdates(), SP2::RTSUpdates(), SP2::shopUpdates(), and SP2::waveTransitionUpdate().
void Application::Exit ()
Definition at line 144 of file Application.cpp.
References m_window.
Referenced by main().
void Application::getMouse (double & x, double & y) static
Definition at line 152 of file Application.cpp.
References m_window.
Referenced by MousePicker::calculateMouseRay(), Camera::DisableCursor(), SP2::shopUpdates(), and SP2::Update().
void Application::hideMouse () static
Definition at line 162 of file Application.cpp.
References m_window.
Referenced by Camera::DisableCursor().
void Application::Init ()
Definition at line 63 of file Application.cpp.
References error_callback(), m_window, resize_callback(), screenHeight, screenWidth, and scrollwheel_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Definition at line 39 of file Application.cpp.
Referenced by SP2::abductionquest(), SP2::asteroidquest(), SP2::ballquest(), SP2::buyshipquest(), Camera::FPSMovement(), SP2::gameOverUpdate(), SP2::generalUpdates(), SP2::inPlayerShipUpdates(), SP2::inSpaceStationUpdates(), SP2::mainMenuUpdates(), SP2::MouseSelection(), Camera::NoClip(), SP2::playerBulletCreation(), SP2::quests(), SP2::RTSUpdates(), SP2::shopUpdates(), Camera::TPSMovement(), Camera::Update(), SP2::Update(), and Camera::YawRotation().
void Application::Run ()
Definition at line 119 of file Application.cpp.
References Scene::Exit(), frameTime, StopWatch::getElapsedTime(), sharedData::GetInstance(), Scene::Init(), m_timer, m_window, Scene::Render(), StopWatch::startTimer(), Scene::Update(), and StopWatch::waitUntil().
Referenced by main().
void Application::showMouse () static
Definition at line 167 of file Application.cpp.
References m_window.
Referenced by Camera::EnableCursor().
Field Documentation
StopWatch Application::m_timer private
Definition at line 32 of file Application.h.
Referenced by Run().
int Application::screenHeight = 0 static
Definition at line 24 of file Application.h.
Referenced by MousePicker::calculateMouseRay(), centerMouse(), Camera::getYawAndPitch(), Init(), SP2::Init(), SP2::shopInit(), SP2::shopUpdates(), and SP2::Update().
int Application::screenWidth = 0 static
Definition at line 23 of file Application.h.
Referenced by MousePicker::calculateMouseRay(), centerMouse(), Camera::getYawAndPitch(), Init(), SP2::Init(), SP2::renderTitleScreen(), SP2::shopInit(), SP2::shopUpdates(), and SP2::Update().
double Application::scrollX = 0 static
Definition at line 26 of file Application.h.
Referenced by scrollwheel_callback().
double Application::scrollY = 0 static
Definition at line 27 of file Application.h.
Referenced by scrollwheel_callback(), and Camera::YawRotation().
The documentation for this class was generated from the following files:
Zyzrag/Source/Application.h
Zyzrag/Source/Application.cpp