My Application: Vehicles Class Reference
Vehicles Class Reference
#include <Vehicles.h>
Public Member Functions
bool checkMaxDistance (Vector3 playerPos)
Vehicles ()
Vehicles (Vector3 endLocation)
Vehicles (Vector3 position, Vector3 viewDirection, float newSpeed, int newHealth, float newFireRate, float newBulletDamage)
~Vehicles ()
float getRotationAngle ()
float getRotationAngle (Vector3 newView)
void update (double dt)
void initialMoveDirection ()
void speedControl (double dt)
void setThrust (float newThrust)
void setNewWayPoint (float x, float z)
void initialMoveDirection (float x, float z)
bool fireBullets (double dt)
Public Member Functions inherited from Object
Object ()
Default constructor.
Object (Vector3 pos, Vector3 view, Vector3 up)
Constuctor.
~Object ()
Destructor.
void SetHitbox (AABB hitbox)
Sets object hitbox.
void SetHitboxSize (float size)
Gives a default size to hitbox size.
void SetHitboxSize (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Gives a default size to hitbox size.
void updateHitbox ()
Updates hitbox by getting object pos added with hitbox size.
void SetInteraction (AABB interaction)
Set interaction hitbox.
void SetInteractionSize (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Gives a default size to interaction hitbox size.
void SetPos (Vector3 position)
Set object's position.
void SetPos (float x, float y, float z)
Set object's position.
void SetView (Vector3 view)
Set View of object.
void SetView (float x, float y, float z)
Set View of object.
void SetUp (Vector3 up)
Set up of object.
void SetUp (Vector3 right, Vector3 view)
Sets up of object by getting the cross of right and view.
void SetUp (float x, float y, float z)
Set up of object.
void SetRight (Vector3 right)
Set right of object.
void SetRight (Vector3 view, Vector3 up)
Set right of object by getting the cross of view and up.
void SetRight (float x, float y, float z)
Set Right of object.
Data Fields
float maxDistance = 5000
int maxHealth
int health
double bulletCooldown
float Yaw
float Pitch
float delay
float initialYaw
double bulletFireRate = 0
double bulletDamage = 0
double bulletCurrCooldown
bool board
bool isDead
pathFinding newVehicle
Asteroid * currAttackTarget
Data Fields inherited from Object
AABB interaction
AABB hitbox
AABB hitboxSize
Vector3 Pos
Vector3 View
Vector3 Up
Vector3 Right
Vector3 InteractionMin
Vector3 InteractionMax
Detailed Description
Name: Vehicles.h
Author
: Wong Keng Han Ashley
Date
: 14 feb 2016
: functions and data for all vehicles
Definition at line 26 of file Vehicles.h.
Constructor & Destructor Documentation
Vehicles::Vehicles ()
Name: Vehicles.cpp
Author
: Wong Keng Han Ashley
Date
: 14 feb 2016
: functions and data for all vehicles
: constructor
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: constructor for vehicals
Definition at line 30 of file Vehicles.cpp.
Vehicles::Vehicles (Vector3 moveDirection)
: overloaded constructor
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: constructor for vehicals
Definition at line 56 of file Vehicles.cpp.
Vehicles::Vehicles (Vector3 position, Vector3 viewDirection, float newSpeed, int newHealth, float newFireRate, float newBulletDamage)
: overloaded constructor
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: overloaded constructor for vehicals
Definition at line 79 of file Vehicles.cpp.
Vehicles::~Vehicles ()
: destructor
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: destructor for vehicals
Definition at line 112 of file Vehicles.cpp.
Member Function Documentation
bool Vehicles::checkMaxDistance (Vector3 playerPos)
: ship Max distance
Author
: Wong Keng Han Ashley
Date
: 28 feb 2016
: returns if the target is in range
Definition at line 354 of file Vehicles.cpp.
bool Vehicles::fireBullets (double dt)
: fire bullets
Author
: Wong Keng Han Ashley
Date
: 23 feb 2016
: returns if the target is in range
Definition at line 321 of file Vehicles.cpp.
Referenced by SP2::shipBulletCreation().
float Vehicles::getRotationAngle ()
: getRotationAngle
Author
: Wong Keng Han Ashley
Date
: 18 feb 2016
: setting initial waypoints for the object
Definition at line 237 of file Vehicles.cpp.
Referenced by SP2::MouseSelection().
float Vehicles::getRotationAngle (Vector3 newView)
: overloaded getRotationAngle
Author
: Wong Keng Han Ashley
Date
: 18 feb 2016
: setting initial waypoints for the object
Definition at line 290 of file Vehicles.cpp.
void Vehicles::initialMoveDirection ()
: overloaded initialMoveDirection
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: setting Initial Move Direction for the object
Definition at line 217 of file Vehicles.cpp.
Referenced by SP2::MouseSelection().
void Vehicles::initialMoveDirection (float x, float z)
: initialMoveDirection
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: setting Initial Move Direction for the object
Definition at line 197 of file Vehicles.cpp.
void Vehicles::setNewWayPoint (float x, float z)
: setNewWayPoint
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: setting waypoints for the object
Definition at line 178 of file Vehicles.cpp.
void Vehicles::setThrust (float newThrust)
: setThrust
Author
: Wong Keng Han Ashley
Date
: 18 feb 2016
: sets the speed of the vehicle
Definition at line 271 of file Vehicles.cpp.
void Vehicles::speedControl (double dt)
: speedControl
Author
: Wong Keng Han Ashley
Date
: 1st March 2016
: reduce speed if it's near asteroid and increase speed when far away
Definition at line 380 of file Vehicles.cpp.
void Vehicles::update (double dt)
: update
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: update the vehicle
Definition at line 129 of file Vehicles.cpp.
Referenced by SP2::MouseSelection().
Field Documentation
bool Vehicles::board
Definition at line 63 of file Vehicles.h.
double Vehicles::bulletCooldown
Definition at line 55 of file Vehicles.h.
double Vehicles::bulletCurrCooldown
Definition at line 60 of file Vehicles.h.
double Vehicles::bulletDamage = 0
Definition at line 59 of file Vehicles.h.
Referenced by SP2::shipBulletCreation().
double Vehicles::bulletFireRate = 0
Definition at line 58 of file Vehicles.h.
Asteroid* Vehicles::currAttackTarget
Definition at line 67 of file Vehicles.h.
Referenced by SP2::MouseSelection(), SP2::selectionRemovetarget(), SP2::selectionSetTarget(), and SP2::shipBulletCreation().
float Vehicles::delay
Definition at line 57 of file Vehicles.h.
int Vehicles::health
Definition at line 33 of file Vehicles.h.
float Vehicles::initialYaw
Definition at line 57 of file Vehicles.h.
Referenced by SP2::MouseSelection(), and SP2::renderShips().
bool Vehicles::isDead
Definition at line 63 of file Vehicles.h.
float Vehicles::maxDistance = 5000
Definition at line 32 of file Vehicles.h.
int Vehicles::maxHealth
Definition at line 33 of file Vehicles.h.
pathFinding Vehicles::newVehicle
Definition at line 65 of file Vehicles.h.
Referenced by SP2::MouseSelection().
float Vehicles::Pitch
Definition at line 57 of file Vehicles.h.
float Vehicles::Yaw
Definition at line 57 of file Vehicles.h.
The documentation for this class was generated from the following files:
Zyzrag/Source/Vehicles.h
Zyzrag/Source/Vehicles.cpp