My Application: Object Class Reference
Object Class Reference
#include <Object.h>
Public Member Functions
Object ()
Default constructor.
Object (Vector3 pos, Vector3 view, Vector3 up)
Constuctor.
~Object ()
Destructor.
void SetHitbox (AABB hitbox)
Sets object hitbox.
void SetHitboxSize (float size)
Gives a default size to hitbox size.
void SetHitboxSize (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Gives a default size to hitbox size.
void updateHitbox ()
Updates hitbox by getting object pos added with hitbox size.
void SetInteraction (AABB interaction)
Set interaction hitbox.
void SetInteractionSize (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Gives a default size to interaction hitbox size.
void SetPos (Vector3 position)
Set object's position.
void SetPos (float x, float y, float z)
Set object's position.
void SetView (Vector3 view)
Set View of object.
void SetView (float x, float y, float z)
Set View of object.
void SetUp (Vector3 up)
Set up of object.
void SetUp (Vector3 right, Vector3 view)
Sets up of object by getting the cross of right and view.
void SetUp (float x, float y, float z)
Set up of object.
void SetRight (Vector3 right)
Set right of object.
void SetRight (Vector3 view, Vector3 up)
Set right of object by getting the cross of view and up.
void SetRight (float x, float y, float z)
Set Right of object.
Data Fields
AABB interaction
AABB hitbox
AABB hitboxSize
Vector3 Pos
Vector3 View
Vector3 Up
Vector3 Right
Vector3 InteractionMin
Vector3 InteractionMax
Detailed Description
Definition at line 6 of file Object.h.
Constructor & Destructor Documentation
Object::Object ()
Default constructor.
Definition at line 23 of file Object.cpp.
Object::Object (Vector3 pos, Vector3 view, Vector3 up)
Constuctor.
Parameters
pos Sets position of object.
view Sets view of object.
up Sets up of object.
Definition at line 43 of file Object.cpp.
References Vector3::Cross(), Pos, Right, Up, and View.
Object::~Object ()
Destructor.
Definition at line 57 of file Object.cpp.
Member Function Documentation
void Object::SetHitbox (AABB hitbox)
Sets object hitbox.
Parameters
hitbox Takes in an AABB class hitbox.
Definition at line 71 of file Object.cpp.
References AABB::GetMax(), AABB::GetMin(), and AABB::Set().
Referenced by SP2::objectsInit().
void Object::SetHitboxSize (float size)
Gives a default size to hitbox size.
Parameters
size Size of hitbox wanted.
Definition at line 85 of file Object.cpp.
References hitboxSize, and AABB::Set().
Referenced by Asteroid::Asteroid(), SP2::generalUpdates(), NPC::NPC(), SP2::npcInit(), SP2::objectsInit(), and SP2::shopUpdates().
void Object::SetHitboxSize (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Gives a default size to hitbox size.
Parameters
minX Min X coordinates.
minY Min Y coordinates.
minZ Min Z coordinates
maxX Max X coordinates.
maxY Max Y coordinates.
maxZ Max Z coordinates.
Definition at line 109 of file Object.cpp.
References hitboxSize, and AABB::Set().
void Object::SetInteraction (AABB interaction)
Set interaction hitbox.
Parameters
interaction Gets an AABB class hitbox.
Definition at line 134 of file Object.cpp.
References interaction.
void Object::SetInteractionSize (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Gives a default size to interaction hitbox size.
Parameters
minX Min X coordinates.
minY Min Y coordinates.
minZ Min Z coordinates
maxX Max X coordinates.
maxY Max Y coordinates.
maxZ Max Z coordinates.
Definition at line 158 of file Object.cpp.
References InteractionMax, and InteractionMin.
Referenced by SP2::shopUpdates().
void Object::SetPos (Vector3 position)
Set object's position.
Parameters
position Vector3 position wanted.
Definition at line 173 of file Object.cpp.
References Pos.
Referenced by SP2::generalUpdates(), SP2::generateAsteroid(), SP2::inPlayerShipUpdates(), SP2::inSpaceStationUpdates(), NPC::NPC(), SP2::npcInit(), SP2::objectsInit(), and SP2::RTSUpdates().
void Object::SetPos (float x, float y, float z)
Set object's position.
Parameters
x X coordinates
y Y coordinates
Z Z coordinates
Definition at line 191 of file Object.cpp.
References Pos, and Vector3::Set().
void Object::SetRight (Vector3 right)
Set right of object.
right Vector3 right wanted.
Definition at line 286 of file Object.cpp.
References Right.
Referenced by SP2::generalUpdates(), SP2::inPlayerShipUpdates(), and SP2::objectsInit().
void Object::SetRight (Vector3 view, Vector3 up)
Set right of object by getting the cross of view and up.
Parameters
view Vector3 view of object.
up Vector3 up of object.
Definition at line 303 of file Object.cpp.
References Vector3::Cross(), and Right.
void Object::SetRight (float x, float y, float z)
Set Right of object.
Parameters
x X coordinates
y Y coordinates
Z Z coordinates
Definition at line 321 of file Object.cpp.
References Right, and Vector3::Set().
void Object::SetUp (Vector3 up)
Set up of object.
Parameters
up Vector3 up wanted.
Definition at line 237 of file Object.cpp.
References Up.
Referenced by SP2::generalUpdates(), SP2::inPlayerShipUpdates(), and SP2::objectsInit().
void Object::SetUp (Vector3 right, Vector3 view)
Sets up of object by getting the cross of right and view.
Parameters
right Passes in the Vector3 right.
view Passes in the Vector3 view.
Definition at line 254 of file Object.cpp.
References Vector3::Cross(), and Up.
void Object::SetUp (float x, float y, float z)
Set up of object.
Parameters
x X coordinates
y Y coordinates
Z Z coordinates
Definition at line 272 of file Object.cpp.
References Vector3::Set(), and Up.
void Object::SetView (Vector3 view)
Set View of object.
Parameters
view Vector3 view wanted.
Definition at line 205 of file Object.cpp.
References View.
Referenced by SP2::generalUpdates(), SP2::generateAsteroid(), SP2::inPlayerShipUpdates(), SP2::inSpaceStationUpdates(), NPC::NPC(), and SP2::objectsInit().
void Object::SetView (float x, float y, float z)
Set View of object.
Parameters
x X coordinates
y Y coordinates
Z Z coordinates
Definition at line 223 of file Object.cpp.
References Vector3::Set(), and View.
void Object::updateHitbox ()
Updates hitbox by getting object pos added with hitbox size.
Definition at line 120 of file Object.cpp.
References AABB::GetMax(), AABB::GetMin(), hitbox, hitboxSize, Pos, and AABB::Set().
Referenced by SP2::generateAsteroid(), SP2::inPlayerShipUpdates(), SP2::NPCUpdates(), SP2::objectsInit(), NPC::update(), PlayerVehicle::update(), and Asteroid::update().
Field Documentation
AABB Object::hitbox
Definition at line 14 of file Object.h.
Referenced by SP2::abductionquest(), SP2::asteroidHitboxCheck(), SP2::ballquest(), SP2::inPlayerShipUpdates(), SP2::MouseSelection(), SP2::quests(), SP2::shipHitboxCheck(), SP2::stationHitboxCheck(), and updateHitbox().
AABB Object::hitboxSize
Definition at line 15 of file Object.h.
Referenced by SetHitboxSize(), and updateHitbox().
AABB Object::interaction
Definition at line 13 of file Object.h.
Referenced by SP2::MouseSelection(), and SetInteraction().
Vector3 Object::InteractionMax
Definition at line 16 of file Object.h.
Referenced by SetInteractionSize().
Vector3 Object::InteractionMin
Definition at line 16 of file Object.h.
Referenced by SetInteractionSize().
Vector3 Object::Pos
Definition at line 16 of file Object.h.
Referenced by SP2::asteroidHitboxCheck(), SP2::ballquest(), SP2::bulletUpdates(), SP2::generateAsteroid(), SP2::inPlayerShipUpdates(), SP2::mainMenuUpdates(), SP2::MouseSelection(), Object(), SP2::playerBulletCreation(), Camera::PointAt(), SP2::renderchildtext(), SP2::renderDistances(), SP2::renderNPC5(), SP2::renderShips(), SP2::renderSkybox(), SP2::renderTextonball(), SP2::RTSUpdates(), SetPos(), SP2::shipBulletCreation(), Camera::TPSMovement(), NPC::update(), PlayerVehicle::update(), Asteroid::update(), updateHitbox(), SP2::waveTransitionUpdate(), and Camera::YawRotation().
Vector3 Object::Right
Definition at line 16 of file Object.h.
Referenced by Object(), SP2::objectsInit(), SP2::renderShips(), SetRight(), and Camera::TPSMovement().
Vector3 Object::Up
Definition at line 16 of file Object.h.
Referenced by Object(), Camera::PointAt(), SetUp(), and Camera::TPSMovement().
Vector3 Object::View
Definition at line 16 of file Object.h.
Referenced by SP2::inPlayerShipUpdates(), SP2::mainMenuUpdates(), SP2::MouseSelection(), Object(), SP2::objectsInit(), SP2::playerBulletCreation(), Camera::PointAt(), SP2::RTSUpdates(), SetView(), SP2::stationHitboxCheck(), Camera::TPSMovement(), NPC::update(), PlayerVehicle::update(), Asteroid::update(), and SP2::waveTransitionUpdate().
The documentation for this class was generated from the following files:
Zyzrag/Source/Object.h
Zyzrag/Source/Object.cpp