My Application: SP2 Class Reference
SP2 Class Reference
#include <SP2.h>
Public Member Functions
SP2 ()
~SP2 ()
virtual void Exit ()
virtual void Init ()
virtual void Render ()
virtual void Update (double dt)
void objectsInit ()
void npcInit ()
void lightInit ()
void shopInit ()
void WorldHitboxInit ()
void bulletCreation (double dt)
void generateAsteroid ()
void shipBulletCreation (double dt)
void playerBulletCreation (double dt)
void renderHelp ()
void renderExit ()
void renderNPC ()
void renderNPC2 ()
void renderNPC3 ()
void renderNPC4 ()
void renderNPC5 ()
void renderShips ()
void renderSkybox ()
void renderStation ()
void renderBullets ()
void renderGeneral ()
void renderShopMenu ()
void renderAsteroid ()
void renderDistances ()
void renderAllHitbox ()
void renderExplosion ()
void renderWayPoints ()
void renderFightingUI ()
void renderExplosions ()
void renderTitleScreen ()
void renderGameOverScreen ()
void renderWaveTransition ()
void renderHealthBar (Vector3 asteroidPosition, int asteroidSize, int health, Color color)
void gameOverUpdate ()
void RTSUpdates (double dt)
void NPCUpdates (double dt)
void shopUpdates (double dt)
void inShopUpdates (double dt)
void bulletUpdates (double dt)
void vehicleUpdates (double dt)
void asteroidUpdate (double dt)
void generalUpdates (double dt)
void mainMenuUpdates (double dt)
void explosionUpdate (double dt)
void inPlayerShipUpdates (double dt)
void waveTransitionUpdate (double dt)
void inSpaceStationUpdates (double dt)
void quests ()
void ballquest ()
void buyshipquest ()
void checkHitboxes ()
void asteroidquest ()
void abductionquest ()
void shipHitboxCheck ()
void stationHitboxCheck ()
void asteroidHitboxCheck ()
void selectionRemovetarget ()
void MouseSelection (double dt)
void renderTextonball ()
void renderchildtext ()
void selectionSetTarget (Asteroid *newTarget)
void vehiclesRemoveTarget (Asteroid *oldTarget)
void selectionSetWaypoints (Vector3 newPosition)
void removeOneSelection (Vehicles *removedVehicle)
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y, float z=0)
void RenderOnScreen (Mesh *mesh, float x, float y, float z, float size, float rotX, float rotY, float rotZ)
void RenderOnScreen (Mesh *mesh, Vector3 pos, float size, float rotX, float rotY, float rotZ)
bool Timer (float second, double dt)
int generate_range (int from, int to)
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_RAY, GEO_LIGHTBALL, GEO_SPHERE,
GEO_TITLESCREEN, GEO_HELPSCREEN, GEO_FRONT, GEO_BACK,
GEO_LEFT, GEO_RIGHT, GEO_TOP, GEO_BOTTOM,
GEO_TEXT, GEO_TEXT1, GEO_TEXT2, GEO_XWING,
GEO_SMALLSHIP, GEO_MIDSHIP, GEO_LARGESHIP, GEO_CONTROL_PANEL,
GEO_SPACE_STATION, GEO_TELEPORTER, GEO_HITBOX, GEO_SHOPBACKDROP,
GEO_ATTACKUP, GEO_FIRERATEUP, GEO_HEALTHUP, GEO_BUYBUTTON,
GEO_NPC, GEO_NPC2, GEO_NPC3, GEO_NPC4,
GEO_NPC5, GEO_NPC6, GEO_NPC7, GEO_LEFTHAND,
GEO_RIGHTHAND, GEO_LEFTLEG, GEO_RIGHTLEG, GEO_BULLETS,
GEO_ASTEROID, GEO_EXPLOSION, GEO_HEALTHBAR, GEO_INNERSTATION,
GEO_SELECTION, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_COSCUTOFF,
U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION, U_LIGHT1_COLOR,
U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ,
U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER,
U_LIGHT1_EXPONENT, U_LIGHT2_POSITION, U_LIGHT2_COLOR, U_LIGHT2_POWER,
U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_TYPE,
U_LIGHT2_SPOTDIRECTION, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT,
U_LIGHTENABLED, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE,
U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
enum GAMESTATE {
MainMenu = 0, RTS, inPlayerShip, inSpaceStation,
inShop, waveTransition, help, gameOver,
exit
}
enum HITBOXCHECK { CheckStation = 0, CheckShips, CheckAsteroids }
enum QUEST {
noQuest = 0, ballQuest, asteroidQuest, buyshipQuest,
abductionQuest
}
enum SHOPSTATE { Main = 0, FirstShip, SecondShip, ThirdShip }
Private Attributes
irrklang::ISoundEngine * shootingsfx = irrklang::createIrrKlangDevice()
irrklang::ISoundEngine * explosionsfx = irrklang::createIrrKlangDevice()
int currMoney
Camera camera
Light light [3]
Vector3 LightView
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_vertexArrayID
unsigned m_parameters [U_TOTAL]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
bool kidnap
bool pickup
bool displayHelp
int destroyed
int shipbought
bool enableLight
bool enableAxis
bool widescreen
float readyToUse
float delay
float second
float screenWidth
float screenHeight
Vector3 shopSmallPos
Vector3 shopMidPos
Vector3 shopLargePos
Vector3 shopTarget
float objSize
float shopSmallScale
float shopMidScale
float shopLargeScale
float shopSmallRot
float shopMidRot
float shopLargeRot
bool hold
Vector3 initCursor
Vector3 endCursor
SHOPSTATE shopState
GAMESTATE state
GAMESTATE lastState
HITBOXCHECK HBcheck
MousePicker picker
Object station
Object LastLocation
Object ball
Object NPC5
string FPSText
Shop * playerShop
map< int, vector< Vehicles * > > allVehicles
map< int, stack< Vehicles * > > storedVehicles
vector< Vehicles * > smallVehicles
vector< Vehicles * > largeVehicles
vector< Vehicles * > midVehicles
vector< NPC * > allNPC
stack< Vehicles * > stackSmallVehicles
stack< Vehicles * > stackLargeVehicles
stack< Vehicles * > stackMidVehicles
PlayerVehicle playerShip
Vehicles * midShip
Vehicles * smallShip
Vehicles * largeShip
vector< Vehicles * > selection
Vehicles * place
int placeType
vector< AABB > worldHitbox
vector< AABB > Interactions
vector< Bullet * > allBullets
vector< Asteroid * > Vasteroid
vector< Explosion * > allExplosions
MS modelStack
MS viewStack
MS projectionStack
QUEST currentQuest = noQuest
Wave * waveFunctions
Detailed Description
Definition at line 40 of file SP2.h.
Member Enumeration Documentation
enum SP2::GAMESTATE private
Enumerator
MainMenu
RTS
inPlayerShip
inSpaceStation
inShop
waveTransition
help
gameOver
exit
Definition at line 156 of file SP2.h.
enum SP2::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_RAY
GEO_LIGHTBALL
GEO_SPHERE
GEO_TITLESCREEN
GEO_HELPSCREEN
GEO_FRONT
GEO_BACK
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_TEXT
GEO_TEXT1
GEO_TEXT2
GEO_XWING
GEO_SMALLSHIP
GEO_MIDSHIP
GEO_LARGESHIP
GEO_CONTROL_PANEL
GEO_SPACE_STATION
GEO_TELEPORTER
GEO_HITBOX
GEO_SHOPBACKDROP
GEO_ATTACKUP
GEO_FIRERATEUP
GEO_HEALTHUP
GEO_BUYBUTTON
GEO_NPC
GEO_NPC2
GEO_NPC3
GEO_NPC4
GEO_NPC5
GEO_NPC6
GEO_NPC7
GEO_LEFTHAND
GEO_RIGHTHAND
GEO_LEFTLEG
GEO_RIGHTLEG
GEO_BULLETS
GEO_ASTEROID
GEO_EXPLOSION
GEO_HEALTHBAR
GEO_INNERSTATION
GEO_SELECTION
NUM_GEOMETRY
Definition at line 42 of file SP2.h.
enum SP2::HITBOXCHECK private
Enumerator
CheckStation
CheckShips
CheckAsteroids
Definition at line 169 of file SP2.h.
enum SP2::QUEST private
Enumerator
noQuest
ballQuest
asteroidQuest
buyshipQuest
abductionQuest
Definition at line 177 of file SP2.h.
enum SP2::SHOPSTATE private
Enumerator
Main
FirstShip
SecondShip
ThirdShip
Definition at line 186 of file SP2.h.
enum SP2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_LIGHTENABLED
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 101 of file SP2.h.
Constructor & Destructor Documentation
SP2::SP2 ()
Definition at line 14 of file SP2.cpp.
SP2::~SP2 ()
Definition at line 20 of file SP2.cpp.
Member Function Documentation
void SP2::abductionquest ()
Definition at line 2819 of file SP2.cpp.
References abductionQuest, allNPC, camera, currentQuest, currMoney, GEO_TEXT2, Object::hitbox, Application::IsKeyPressed(), kidnap, meshList, NPC5, AABB::PointToAABB(), Camera::position, renderchildtext(), and RenderTextOnScreen().
Referenced by Render().
void SP2::asteroidHitboxCheck ()
Definition at line 2397 of file SP2.cpp.
References allBullets, allExplosions, allVehicles, currMoney, destroyed, explosionsfx, GEO_LARGESHIP, GEO_SMALLSHIP, PlayerVehicle::health, Object::hitbox, Wave::numberOfAsteroidsDestroyed, irrklang::ISoundEngine::play3D(), playerShip, Object::Pos, removeOneSelection(), Asteroid::size, Vasteroid, vehiclesRemoveTarget(), waveFunctions, Vector3::x, Vector3::y, and Vector3::z.
Referenced by checkHitboxes().
void SP2::asteroidquest ()
Definition at line 2773 of file SP2.cpp.
References allNPC, asteroidQuest, camera, currentQuest, currMoney, GEO_TEXT2, Application::IsKeyPressed(), meshList, Camera::position, and RenderTextOnScreen().
Referenced by Render().
void SP2::asteroidUpdate (double dt)
Definition at line 1978 of file SP2.cpp.
References Asteroid::curRange, generateAsteroid(), Asteroid::health, Asteroid::maxRange, Wave::numberOfAsteroidsDestroyed, Timer(), Asteroid::update(), Vasteroid, vehiclesRemoveTarget(), and waveFunctions.
Referenced by generalUpdates().
void SP2::ballquest ()
Definition at line 2733 of file SP2.cpp.
References allNPC, ball, ballQuest, camera, currentQuest, currMoney, enableLight, GEO_SPHERE, GEO_TEXT2, Object::hitbox, Application::IsKeyPressed(), meshList, modelStack, pickup, AABB::PointToAABB(), MS::PopMatrix(), Object::Pos, Camera::position, MS::PushMatrix(), RenderMesh(), RenderOnScreen(), renderTextonball(), RenderTextOnScreen(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::bulletCreation (double dt)
void SP2::bulletUpdates (double dt)
Definition at line 1952 of file SP2.cpp.
References allBullets, allExplosions, Bullet::bulletUpdate(), Bullet::furtherThanBulletMaxRange(), and Object::Pos.
Referenced by generalUpdates().
void SP2::buyshipquest ()
Definition at line 2796 of file SP2.cpp.
References allNPC, buyshipQuest, camera, currentQuest, currMoney, GEO_TEXT2, Application::IsKeyPressed(), meshList, Camera::position, and RenderTextOnScreen().
Referenced by Render().
void SP2::checkHitboxes ()
Definition at line 2220 of file SP2.cpp.
References asteroidHitboxCheck(), CheckAsteroids, CheckShips, CheckStation, HBcheck, shipHitboxCheck(), and stationHitboxCheck().
Referenced by generalUpdates().
void SP2::Exit () virtual
Implements Scene.
Definition at line 558 of file SP2.cpp.
References allBullets, allExplosions, allNPC, allVehicles, GEO_LARGESHIP, GEO_SMALLSHIP, m_programID, m_vertexArrayID, playerShop, storedVehicles, and Vasteroid.
Referenced by gameOverUpdate(), and Update().
void SP2::explosionUpdate (double dt)
Definition at line 2060 of file SP2.cpp.
References allExplosions, camera, Vector3::Cross(), Vector3::Dot(), Vector3::Normalize(), Camera::position, Math::RadianToDegree(), Vector3::Set(), Mtx44::SetToRotation(), Camera::target, Vector3::x, and Vector3::z.
Referenced by generalUpdates().
void SP2::gameOverUpdate ()
Definition at line 1592 of file SP2.cpp.
References Exit(), sharedData::GetInstance(), Init(), Application::IsKeyPressed(), and sharedData::quit.
Referenced by Update().
void SP2::generalUpdates (double dt)
Definition at line 2008 of file SP2.cpp.
References asteroidUpdate(), bulletUpdates(), camera, checkHitboxes(), explosionsfx, explosionUpdate(), sharedData::GetInstance(), help, Application::IsKeyPressed(), lastState, playerShip, Camera::position, PlayerVehicle::reset(), PlayerVehicle::respawn(), Object::SetHitboxSize(), irrklang::ISoundEngine::setListenerPosition(), Object::SetPos(), Object::SetRight(), Object::SetUp(), Object::SetView(), shootingsfx, state, PlayerVehicle::update(), vehicleUpdates(), Camera::view, Wave::waveComplete(), waveFunctions, waveTransition, Wave::waveUpdate(), worldHitbox, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
int SP2::generate_range (int from, int to)
Definition at line 3140 of file SP2.cpp.
Referenced by generateAsteroid().
void SP2::generateAsteroid ()
Definition at line 834 of file SP2.cpp.
References camera, generate_range(), Wave::maxNumberOfAsteroids, Wave::numberOfAsteroidsDestroyed, Object::Pos, Camera::position, Object::SetPos(), Object::SetView(), Wave::spawnAsteroid(), Object::updateHitbox(), Vasteroid, waveFunctions, Wave::waveNumber, Vector3::x, and Vector3::z.
Referenced by asteroidUpdate().
void SP2::Init () virtual
Implements Scene.
Definition at line 25 of file SP2.cpp.
References camera, currMoney, destroyed, displayHelp, enableLight, explosionsfx, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ASTEROID, GEO_ATTACKUP, GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_BULLETS, GEO_CONTROL_PANEL, GEO_EXPLOSION, GEO_FIRERATEUP, GEO_FRONT, GEO_HEALTHUP, GEO_HELPSCREEN, GEO_INNERSTATION, GEO_LARGESHIP, GEO_LEFT, GEO_LEFTHAND, GEO_LEFTLEG, GEO_LIGHTBALL, GEO_MIDSHIP, GEO_NPC, GEO_NPC2, GEO_NPC3, GEO_NPC4, GEO_NPC5, GEO_RIGHT, GEO_RIGHTHAND, GEO_RIGHTLEG, GEO_SHOPBACKDROP, GEO_SMALLSHIP, GEO_SPACE_STATION, GEO_SPHERE, GEO_TELEPORTER, GEO_TEXT, GEO_TEXT1, GEO_TEXT2, GEO_TITLESCREEN, GEO_TOP, GEO_XWING, Camera::Init(), kidnap, lightInit(), LightView, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, MainMenu, meshList, npcInit(), objectsInit(), pickup, place, placeType, projectionStack, readyToUse, Application::screenHeight, screenHeight, Application::screenWidth, screenWidth, irrklang::ISoundEngine::setDefault3DSoundMaxDistance(), irrklang::ISoundEngine::setDefault3DSoundMinDistance(), irrklang::ISoundEngine::setSoundVolume(), Mtx44::SetToPerspective(), shipbought, shootingsfx, shopInit(), state, Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, widescreen, and WorldHitboxInit().
Referenced by gameOverUpdate(), and Update().
void SP2::inPlayerShipUpdates (double dt)
Definition at line 2110 of file SP2.cpp.
References AABB::AABBtoAABB(), camera, Camera::DisableCursor(), sharedData::GetInstance(), Object::hitbox, Camera::Init(), inPlayerShip, inSpaceStation, Interactions, PlayerVehicle::isDead, Application::IsKeyPressed(), LastLocation, lastState, PlayerVehicle::pitch, playerBulletCreation(), playerShip, Camera::PointAt(), Object::Pos, RTS, Object::SetPos(), Object::SetRight(), Object::SetUp(), Object::SetView(), shipBulletCreation(), state, PlayerVehicle::thrust, Camera::TPSMovement(), Object::updateHitbox(), Object::View, and PlayerVehicle::yaw.
Referenced by Update().
void SP2::inShopUpdates (double dt)
Definition at line 1923 of file SP2.cpp.
References camera, Camera::EnableCursor(), and shopUpdates().
Referenced by Update().
void SP2::inSpaceStationUpdates (double dt)
Definition at line 2185 of file SP2.cpp.
References camera, Camera::DisableCursor(), Camera::FPSMovement(), sharedData::GetInstance(), inPlayerShip, inShop, inSpaceStation, Interactions, PlayerVehicle::isDead, Application::IsKeyPressed(), LastLocation, lastState, NPCUpdates(), playerShip, Camera::PointAt(), Camera::position, RTS, Object::SetPos(), Object::SetView(), state, Camera::view, worldHitbox, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SP2::lightInit ()
Definition at line 682 of file SP2.cpp.
References Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, m_parameters, Light::position, Light::power, Position::Set(), Color::Set(), Vector3::Set(), Light::spotDirection, Light::type, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POWER, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POWER, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POWER, U_LIGHT2_TYPE, and U_NUMLIGHTS.
Referenced by Init().
void SP2::mainMenuUpdates (double dt)
Definition at line 2047 of file SP2.cpp.
References camera, Application::centerMouse(), Camera::EnableCursor(), sharedData::GetInstance(), Camera::Init(), inSpaceStation, Application::IsKeyPressed(), LastLocation, Object::Pos, state, and Object::View.
Referenced by Update().
void SP2::MouseSelection (double dt)
Definition at line 2592 of file SP2.cpp.
References allVehicles, camera, Vehicles::currAttackTarget, endCursor, GEO_LARGESHIP, GEO_SMALLSHIP, MousePicker::getCurrentRay(), Vehicles::getRotationAngle(), Object::hitbox, hold, initCursor, Vehicles::initialMoveDirection(), Vehicles::initialYaw, Object::interaction, Application::IsKeyPressed(), Vehicles::newVehicle, Vector3::Normalize(), picker, place, placeType, Object::Pos, Camera::position, AABB::RayToAABB(), pathFinding::resetWayPoints(), selection, selectionSetTarget(), selectionSetWaypoints(), Vector3::Set(), pathFinding::setCurrentLocation(), pathFinding::setCurrSpeed(), Vector3::SetZero(), storedVehicles, Vehicles::update(), Vasteroid, Object::View, AABB::withinPlane(), MousePicker::WorldCoord(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by RTSUpdates().
void SP2::npcInit ()
Definition at line 648 of file SP2.cpp.
References allNPC, ball, destroyed, GEO_NPC, GEO_NPC2, GEO_NPC3, GEO_NPC4, NPC5, NPC::questCompleteDialogue, NPC::questDialogue, NPC::questName, Object::SetHitboxSize(), and Object::SetPos().
Referenced by Init().
void SP2::NPCUpdates (double dt)
Definition at line 1679 of file SP2.cpp.
References allNPC, ball, NPC5, and Object::updateHitbox().
Referenced by inSpaceStationUpdates().
void SP2::objectsInit ()
Definition at line 616 of file SP2.cpp.
References allVehicles, GEO_LARGESHIP, GEO_MIDSHIP, GEO_SMALLSHIP, largeVehicles, LastLocation, midVehicles, playerShip, PlayerVehicle::reset(), Object::Right, Object::SetHitbox(), Object::SetHitboxSize(), Object::SetPos(), Object::SetRight(), Object::SetUp(), Object::SetView(), smallVehicles, stackLargeVehicles, stackMidVehicles, stackSmallVehicles, station, storedVehicles, Object::updateHitbox(), Object::View, and waveFunctions.
Referenced by Init().
void SP2::playerBulletCreation (double dt)
Definition at line 818 of file SP2.cpp.
References allBullets, PlayerVehicle::bulletDamage, PlayerVehicle::fireBullets(), Application::IsKeyPressed(), irrklang::ISoundEngine::play3D(), playerShip, Object::Pos, shootingsfx, Object::View, Vector3::x, Vector3::y, and Vector3::z.
Referenced by inPlayerShipUpdates().
void SP2::quests ()
Definition at line 1609 of file SP2.cpp.
References abductionQuest, allNPC, asteroidQuest, ball, ballQuest, buyshipQuest, camera, currentQuest, destroyed, GEO_TEXT2, Object::hitbox, Application::IsKeyPressed(), kidnap, meshList, pickup, AABB::PointToAABB(), Camera::position, RenderTextOnScreen(), and shipbought.
Referenced by Render(), and Update().
void SP2::removeOneSelection (Vehicles * removedVehicle)
Definition at line 2922 of file SP2.cpp.
References GEO_LARGESHIP, GEO_SMALLSHIP, and selection.
Referenced by asteroidHitboxCheck(), shipHitboxCheck(), and stationHitboxCheck().
void SP2::Render () virtual
Implements Scene.
Definition at line 447 of file SP2.cpp.
References abductionquest(), asteroidquest(), ballquest(), buyshipquest(), camera, enableAxis, endCursor, exit, FPSText, gameOver, MeshBuilder::GenerateSquare(), GEO_AXES, GEO_SELECTION, GEO_TEXT, help, initCursor, inPlayerShip, inShop, inSpaceStation, light, MS::LoadIdentity(), MS::LookAt(), m_parameters, MainMenu, meshList, modelStack, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), quests(), renderAllHitbox(), renderDistances(), renderExit(), renderFightingUI(), renderGameOverScreen(), renderGeneral(), renderHelp(), RenderMesh(), renderNPC(), renderNPC5(), renderShopMenu(), RenderTextOnScreen(), renderTitleScreen(), renderWaveTransition(), RTS, Light::spotDirection, state, Camera::target, MS::Top(), U_LIGHT0_POSITION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, U_LIGHT2_POSITION, U_LIGHT2_SPOTDIRECTION, Camera::up, viewStack, waveTransition, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SP2::renderAllHitbox ()
Definition at line 1179 of file SP2.cpp.
References allVehicles, GEO_LARGESHIP, and GEO_SMALLSHIP.
Referenced by Render().
void SP2::renderAsteroid ()
Definition at line 1214 of file SP2.cpp.
References enableLight, GEO_ASTEROID, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderHealthBar(), RenderMesh(), MS::Scale(), MS::Translate(), and Vasteroid.
Referenced by renderGeneral().
void SP2::renderBullets ()
Definition at line 1197 of file SP2.cpp.
References allBullets, GEO_BULLETS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
Referenced by renderGeneral().
void SP2::renderchildtext ()
Definition at line 1510 of file SP2.cpp.
References camera, Vector3::Cross(), Vector3::Dot(), GEO_TEXT2, meshList, modelStack, Vector3::Normalize(), NPC5, MS::PopMatrix(), Object::Pos, Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderText(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by abductionquest().
void SP2::renderDistances ()
Definition at line 1301 of file SP2.cpp.
References camera, Vector3::Cross(), Vector3::distanceBetween2points(), Vector3::Dot(), GEO_TEXT, meshList, modelStack, Vector3::Normalize(), playerShip, MS::PopMatrix(), Object::Pos, Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderText(), MS::Rotate(), MS::Scale(), station, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::renderExit ()
Definition at line 882 of file SP2.cpp.
References GEO_HELPSCREEN, GEO_TEXT, meshList, objSize, RenderOnScreen(), RenderTextOnScreen(), screenHeight, and screenWidth.
Referenced by Render().
void SP2::renderExplosion ()
Definition at line 1235 of file SP2.cpp.
References allExplosions, GEO_EXPLOSION, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by renderGeneral().
void SP2::renderExplosions ()
void SP2::renderFightingUI ()
Definition at line 1145 of file SP2.cpp.
References currMoney, Wave::currWaveCooldownTime, displayHelp, GEO_LARGESHIP, GEO_MIDSHIP, GEO_SMALLSHIP, GEO_TEXT, PlayerVehicle::health, inShop, Wave::maxNumberOfAsteroids, Wave::maxWaveCooldownTime, meshList, Wave::numberOfAsteroidsDestroyed, objSize, playerShip, RenderTextOnScreen(), RTS, screenHeight, screenWidth, state, Wave::stationHealth, storedVehicles, PlayerVehicle::thrust, and waveFunctions.
Referenced by Render().
void SP2::renderGameOverScreen ()
Definition at line 891 of file SP2.cpp.
References GEO_HELPSCREEN, GEO_TEXT, meshList, objSize, RenderOnScreen(), RenderTextOnScreen(), screenHeight, and screenWidth.
Referenced by Render().
void SP2::renderGeneral ()
Definition at line 1410 of file SP2.cpp.
References renderAsteroid(), renderBullets(), renderExplosion(), renderShips(), renderSkybox(), renderStation(), and renderWayPoints().
Referenced by Render().
void SP2::renderHealthBar (Vector3 asteroidPosition, int asteroidSize, int health, Color color)
Definition at line 1252 of file SP2.cpp.
References camera, Vector3::Cross(), Vector3::Dot(), MeshBuilder::GenerateQuad(), GEO_HEALTHBAR, meshList, modelStack, Vector3::Normalize(), MS::PopMatrix(), Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderMesh(), MS::Rotate(), MS::Scale(), Vector3::Set(), Mtx44::SetToRotation(), Camera::target, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by renderAsteroid(), and renderShips().
void SP2::renderHelp ()
Definition at line 910 of file SP2.cpp.
References GEO_HELPSCREEN, GEO_TEXT, meshList, objSize, RenderOnScreen(), RenderTextOnScreen(), screenHeight, and screenWidth.
Referenced by Render().
void SP2::RenderMesh (Mesh * mesh, bool enableLight)
Definition at line 2951 of file SP2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by ballquest(), Render(), renderAsteroid(), renderBullets(), renderExplosion(), renderHealthBar(), renderNPC(), renderNPC5(), renderShips(), renderSkybox(), renderStation(), and renderWayPoints().
void SP2::renderNPC ()
Definition at line 1422 of file SP2.cpp.
References allNPC, enableLight, GEO_LEFTHAND, GEO_LEFTLEG, GEO_RIGHTHAND, GEO_RIGHTLEG, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SP2::renderNPC2 ()
void SP2::renderNPC3 ()
void SP2::renderNPC4 ()
void SP2::renderNPC5 ()
Definition at line 1476 of file SP2.cpp.
References enableLight, GEO_LEFTLEG, GEO_NPC5, GEO_RIGHTLEG, kidnap, meshList, modelStack, NPC5, MS::PopMatrix(), Object::Pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::RenderOnScreen (Mesh * mesh, float x, float y, float z, float size, float rotX, float rotY, float rotZ)
Definition at line 3063 of file SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Mesh::Render(), MS::Rotate(), MS::Scale(), screenHeight, screenWidth, Mtx44::SetToOrtho(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, and viewStack.
Referenced by ballquest(), renderExit(), renderGameOverScreen(), renderHelp(), renderShopMenu(), renderTitleScreen(), and renderWaveTransition().
void SP2::RenderOnScreen (Mesh * mesh, Vector3 pos, float size, float rotX, float rotY, float rotZ)
Definition at line 3096 of file SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Mesh::Render(), MS::Rotate(), MS::Scale(), screenHeight, screenWidth, Mtx44::SetToOrtho(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void SP2::renderShips ()
Definition at line 1017 of file SP2.cpp.
References allVehicles, enableLight, MeshBuilder::GenerateSquare(), GEO_HITBOX, GEO_LARGESHIP, GEO_SMALLSHIP, GEO_XWING, Vehicles::initialYaw, PlayerVehicle::isDead, meshList, modelStack, PlayerVehicle::pitch, place, placeType, playerShip, MS::PopMatrix(), Object::Pos, MS::PushMatrix(), renderHealthBar(), RenderMesh(), Object::Right, MS::Rotate(), selection, MS::Translate(), Vector3::x, Vector3::y, PlayerVehicle::yaw, and Vector3::z.
Referenced by renderGeneral().
void SP2::renderShopMenu ()
Definition at line 1081 of file SP2.cpp.
References allVehicles, PlayerVehicle::bulletDamage, PlayerVehicle::bulletFireRate, Shop::damageUpgradePrice, Shop::fireRateUpgradePrice, FirstShip, GEO_ATTACKUP, GEO_FIRERATEUP, GEO_HEALTHUP, GEO_LARGESHIP, GEO_MIDSHIP, GEO_SHOPBACKDROP, GEO_SMALLSHIP, GEO_TEXT, Shop::healthUpgradePrice, Main, meshList, objSize, playerShip, playerShop, RenderOnScreen(), RenderTextOnScreen(), screenHeight, screenWidth, SecondShip, shopLargePos, shopLargeRot, shopLargeScale, shopMidPos, shopMidRot, shopMidScale, shopSmallPos, shopSmallRot, shopSmallScale, shopState, storedVehicles, and ThirdShip.
Referenced by Render().
void SP2::renderSkybox ()
Definition at line 933 of file SP2.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, playerShip, MS::PopMatrix(), Object::Pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by renderGeneral().
void SP2::renderStation ()
Definition at line 992 of file SP2.cpp.
References enableLight, GEO_CONTROL_PANEL, GEO_INNERSTATION, GEO_SPACE_STATION, GEO_TELEPORTER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
Referenced by renderGeneral().
void SP2::RenderText (Mesh * mesh, std::string text, Color color)
Definition at line 2992 of file SP2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by renderchildtext(), renderDistances(), and renderTextonball().
void SP2::renderTextonball ()
Definition at line 1548 of file SP2.cpp.
References ball, camera, Vector3::Cross(), Vector3::Dot(), GEO_TEXT, meshList, modelStack, Vector3::Normalize(), MS::PopMatrix(), Object::Pos, Camera::position, MS::PushMatrix(), Math::RadianToDegree(), RenderText(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by ballquest().
void SP2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y, float z = 0)
Definition at line 3019 of file SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), screenHeight, screenWidth, Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by abductionquest(), asteroidquest(), ballquest(), buyshipquest(), quests(), Render(), renderExit(), renderFightingUI(), renderGameOverScreen(), renderHelp(), renderShopMenu(), renderTitleScreen(), and renderWaveTransition().
void SP2::renderTitleScreen ()
Definition at line 1133 of file SP2.cpp.
References GEO_TEXT, GEO_TEXT1, GEO_TITLESCREEN, meshList, modelStack, objSize, MS::PopMatrix(), MS::PushMatrix(), RenderOnScreen(), RenderTextOnScreen(), screenHeight, Application::screenWidth, and screenWidth.
Referenced by Render().
void SP2::renderWaveTransition ()
Definition at line 901 of file SP2.cpp.
References GEO_HELPSCREEN, GEO_TEXT, meshList, objSize, RenderOnScreen(), RenderTextOnScreen(), screenHeight, screenWidth, waveFunctions, and Wave::waveNumber.
Referenced by Render().
void SP2::renderWayPoints ()
Definition at line 1385 of file SP2.cpp.
References allVehicles, GEO_LARGESHIP, GEO_LIGHTBALL, GEO_SMALLSHIP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), and MS::Translate().
Referenced by renderGeneral().
void SP2::RTSUpdates (double dt)
Definition at line 1689 of file SP2.cpp.
References camera, Application::centerMouse(), sharedData::Delay(), Camera::EnableCursor(), GEO_LARGESHIP, GEO_MIDSHIP, GEO_SMALLSHIP, sharedData::GetInstance(), hold, Camera::Init(), inPlayerShip, inSpaceStation, Application::IsKeyPressed(), LastLocation, lastState, MouseSelection(), picker, place, placeType, playerShip, Camera::PointAt(), Object::Pos, projectionStack, selection, MousePicker::set(), Object::SetPos(), shipBulletCreation(), state, storedVehicles, MS::Top(), MousePicker::update(), Object::View, MousePicker::WorldCoord(), and Camera::YawRotation().
Referenced by Update().
void SP2::selectionRemovetarget ()
Definition at line 2868 of file SP2.cpp.
References allVehicles, Vehicles::currAttackTarget, GEO_LARGESHIP, and GEO_SMALLSHIP.
void SP2::selectionSetTarget (Asteroid * newTarget)
Definition at line 2853 of file SP2.cpp.
References Vehicles::currAttackTarget, and selection.
Referenced by MouseSelection().
void SP2::selectionSetWaypoints (Vector3 newPosition)
Definition at line 2908 of file SP2.cpp.
References selection, Vector3::x, and Vector3::z.
Referenced by MouseSelection().
void SP2::shipBulletCreation (double dt)
Definition at line 791 of file SP2.cpp.
References allBullets, allVehicles, Vehicles::bulletDamage, Vehicles::currAttackTarget, Vehicles::fireBullets(), GEO_LARGESHIP, GEO_SMALLSHIP, Vector3::Normalize(), irrklang::ISoundEngine::play3D(), Object::Pos, shootingsfx, Vector3::x, Vector3::y, and Vector3::z.
Referenced by inPlayerShipUpdates(), and RTSUpdates().
void SP2::shipHitboxCheck ()
Definition at line 2246 of file SP2.cpp.
References allExplosions, allVehicles, explosionsfx, GEO_LARGESHIP, GEO_SMALLSHIP, Object::hitbox, irrklang::ISoundEngine::play3D(), playerShip, removeOneSelection(), and storedVehicles.
Referenced by checkHitboxes().
void SP2::shopInit ()
Definition at line 752 of file SP2.cpp.
References Main, objSize, playerShip, playerShop, Application::screenHeight, screenHeight, Application::screenWidth, screenWidth, Vector3::Set(), shopLargePos, shopLargeRot, shopLargeScale, shopMidPos, shopMidRot, shopMidScale, shopSmallPos, shopSmallRot, shopSmallScale, and shopState.
Referenced by Init().
void SP2::shopUpdates (double dt)
Definition at line 1748 of file SP2.cpp.
References Application::centerMouse(), currMoney, Shop::damageUpgradePrice, Shop::fireRateUpgradePrice, FirstShip, GEO_LARGESHIP, GEO_MIDSHIP, GEO_SMALLSHIP, sharedData::GetInstance(), Application::getMouse(), Shop::healthUpgradePrice, Shop::increaseDamage(), Shop::increaseFireRate(), Shop::increaseHealth(), inSpaceStation, Application::IsKeyPressed(), largeShip, Main, midShip, Vector3::Normalize(), objSize, playerShop, Application::screenHeight, screenHeight, Application::screenWidth, screenWidth, SecondShip, Vector3::Set(), Object::SetHitboxSize(), Object::SetInteractionSize(), shipbought, shopLargePos, shopLargeRot, shopLargeScale, shopMidPos, shopMidRot, shopMidScale, shopSmallPos, shopSmallRot, shopSmallScale, shopState, shopTarget, smallShip, state, storedVehicles, ThirdShip, Vector3::x, and Vector3::y.
Referenced by inShopUpdates().
void SP2::stationHitboxCheck ()
Definition at line 2350 of file SP2.cpp.
References AABB::AABBtoAABB(), allExplosions, allVehicles, explosionsfx, GEO_LARGESHIP, GEO_SMALLSHIP, Object::hitbox, Wave::numberOfAsteroidsDestroyed, irrklang::ISoundEngine::play3D(), removeOneSelection(), station, Wave::stationHealth, storedVehicles, Vasteroid, vehiclesRemoveTarget(), Object::View, and waveFunctions.
Referenced by checkHitboxes().
bool SP2::Timer (float second, double dt)
Definition at line 3129 of file SP2.cpp.
Referenced by asteroidUpdate().
void SP2::Update (double dt) virtual
Implements Scene.
Definition at line 275 of file SP2.cpp.
References camera, Wave::currWaveCooldownTime, sharedData::DelayIncrement(), enableAxis, Camera::EnableCursor(), enableLight, exit, Exit(), FPSText, gameOver, gameOverUpdate(), generalUpdates(), sharedData::GetInstance(), Application::getMouse(), HBcheck, help, Init(), inPlayerShip, inPlayerShipUpdates(), inShop, inShopUpdates(), inSpaceStation, inSpaceStationUpdates(), Application::IsKeyPressed(), lastState, light, m_parameters, MainMenu, mainMenuUpdates(), Wave::maxWaveCooldownTime, Light::power, quests(), sharedData::quit, readyToUse, RTS, RTSUpdates(), Application::screenHeight, screenHeight, Application::screenWidth, screenWidth, Vector3::Set(), Mtx44::SetToRotation(), Light::spotDirection, state, Wave::stationHealth, U_LIGHT1_POWER, U_LIGHT2_POWER, Camera::Update(), waveFunctions, waveTransition, and waveTransitionUpdate().
void SP2::vehiclesRemoveTarget (Asteroid * oldTarget)
Definition at line 2886 of file SP2.cpp.
References allVehicles, GEO_LARGESHIP, and GEO_SMALLSHIP.
Referenced by asteroidHitboxCheck(), asteroidUpdate(), and stationHitboxCheck().
void SP2::vehicleUpdates (double dt)
Definition at line 1929 of file SP2.cpp.
References allVehicles, camera, GEO_LARGESHIP, GEO_SMALLSHIP, and Camera::position.
Referenced by generalUpdates().
void SP2::waveTransitionUpdate (double dt)
Definition at line 2153 of file SP2.cpp.
References camera, Application::centerMouse(), currMoney, Wave::endOfTransition, Camera::Init(), inPlayerShip, inSpaceStation, LastLocation, lastState, playerShip, Camera::PointAt(), Object::Pos, RTS, state, Object::View, waveFunctions, Wave::waveNumber, and Wave::waveUpdate().
Referenced by Update().
void SP2::WorldHitboxInit ()
Definition at line 773 of file SP2.cpp.
References Interactions, and worldHitbox.
Referenced by Init().
Field Documentation
vector<Bullet*> SP2::allBullets private
Definition at line 379 of file SP2.h.
Referenced by asteroidHitboxCheck(), bulletUpdates(), Exit(), playerBulletCreation(), renderBullets(), and shipBulletCreation().
vector<Explosion*> SP2::allExplosions private
Definition at line 381 of file SP2.h.
Referenced by asteroidHitboxCheck(), bulletUpdates(), Exit(), explosionUpdate(), renderExplosion(), shipHitboxCheck(), and stationHitboxCheck().
vector<NPC*> SP2::allNPC private
Definition at line 360 of file SP2.h.
Referenced by abductionquest(), asteroidquest(), ballquest(), buyshipquest(), Exit(), npcInit(), NPCUpdates(), quests(), and renderNPC().
map<int, vector<Vehicles*> > SP2::allVehicles private
Definition at line 353 of file SP2.h.
Referenced by asteroidHitboxCheck(), Exit(), MouseSelection(), objectsInit(), renderAllHitbox(), renderShips(), renderShopMenu(), renderWayPoints(), selectionRemovetarget(), shipBulletCreation(), shipHitboxCheck(), stationHitboxCheck(), vehiclesRemoveTarget(), and vehicleUpdates().
Object SP2::ball private
Definition at line 346 of file SP2.h.
Referenced by ballquest(), npcInit(), NPCUpdates(), quests(), and renderTextonball().
Camera SP2::camera private
Definition at line 300 of file SP2.h.
Referenced by abductionquest(), asteroidquest(), ballquest(), buyshipquest(), explosionUpdate(), generalUpdates(), generateAsteroid(), Init(), inPlayerShipUpdates(), inShopUpdates(), inSpaceStationUpdates(), mainMenuUpdates(), MouseSelection(), quests(), Render(), renderchildtext(), renderDistances(), renderHealthBar(), renderTextonball(), RTSUpdates(), Update(), vehicleUpdates(), and waveTransitionUpdate().
QUEST SP2::currentQuest = noQuest private
Definition at line 385 of file SP2.h.
Referenced by abductionquest(), asteroidquest(), ballquest(), buyshipquest(), and quests().
int SP2::currMoney private
Definition at line 298 of file SP2.h.
Referenced by abductionquest(), asteroidHitboxCheck(), asteroidquest(), ballquest(), buyshipquest(), Init(), renderFightingUI(), shopUpdates(), and waveTransitionUpdate().
float SP2::delay private
Definition at line 322 of file SP2.h.
int SP2::destroyed private
Definition at line 317 of file SP2.h.
Referenced by asteroidHitboxCheck(), Init(), npcInit(), and quests().
bool SP2::displayHelp private
Definition at line 315 of file SP2.h.
Referenced by Init(), and renderFightingUI().
bool SP2::enableAxis private
Definition at line 320 of file SP2.h.
Referenced by Render(), and Update().
bool SP2::enableLight private
Definition at line 320 of file SP2.h.
Referenced by ballquest(), Init(), renderAsteroid(), renderNPC(), renderNPC5(), renderShips(), renderStation(), and Update().
Vector3 SP2::endCursor private
Definition at line 333 of file SP2.h.
Referenced by MouseSelection(), and Render().
irrklang::ISoundEngine* SP2::explosionsfx = irrklang::createIrrKlangDevice() private
Definition at line 296 of file SP2.h.
Referenced by asteroidHitboxCheck(), generalUpdates(), Init(), shipHitboxCheck(), and stationHitboxCheck().
string SP2::FPSText private
Definition at line 349 of file SP2.h.
Referenced by Render(), and Update().
HITBOXCHECK SP2::HBcheck private
Definition at line 340 of file SP2.h.
Referenced by checkHitboxes(), and Update().
bool SP2::hold private
Definition at line 332 of file SP2.h.
Referenced by MouseSelection(), and RTSUpdates().
Vector3 SP2::initCursor private
Definition at line 333 of file SP2.h.
Referenced by MouseSelection(), and Render().
vector<AABB> SP2::Interactions private
Definition at line 378 of file SP2.h.
Referenced by inPlayerShipUpdates(), inSpaceStationUpdates(), and WorldHitboxInit().
bool SP2::kidnap private
Definition at line 312 of file SP2.h.
Referenced by abductionquest(), Init(), quests(), and renderNPC5().
Vehicles* SP2::largeShip private
Definition at line 370 of file SP2.h.
Referenced by shopUpdates().
vector<Vehicles*> SP2::largeVehicles private
Definition at line 357 of file SP2.h.
Referenced by objectsInit().
Object SP2::LastLocation private
Definition at line 345 of file SP2.h.
Referenced by inPlayerShipUpdates(), inSpaceStationUpdates(), mainMenuUpdates(), objectsInit(), RTSUpdates(), and waveTransitionUpdate().
GAMESTATE SP2::lastState private
Definition at line 338 of file SP2.h.
Referenced by generalUpdates(), inPlayerShipUpdates(), inSpaceStationUpdates(), RTSUpdates(), Update(), and waveTransitionUpdate().
Light SP2::light[3] private
Definition at line 301 of file SP2.h.
Referenced by lightInit(), Render(), and Update().
Vector3 SP2::LightView private
Definition at line 302 of file SP2.h.
Referenced by Init().
unsigned SP2::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 308 of file SP2.h.
unsigned SP2::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 309 of file SP2.h.
unsigned SP2::m_parameters[U_TOTAL] private
Definition at line 307 of file SP2.h.
Referenced by Init(), lightInit(), Render(), RenderMesh(), RenderOnScreen(), RenderText(), RenderTextOnScreen(), and Update().
unsigned SP2::m_programID private
Definition at line 305 of file SP2.h.
Referenced by Exit(), and Init().
unsigned SP2::m_vertexArrayID private
Definition at line 306 of file SP2.h.
Referenced by Exit(), and Init().
unsigned SP2::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 310 of file SP2.h.
Mesh* SP2::meshList[NUM_GEOMETRY] private
Definition at line 303 of file SP2.h.
Referenced by abductionquest(), asteroidquest(), ballquest(), buyshipquest(), Init(), quests(), Render(), renderAsteroid(), renderBullets(), renderchildtext(), renderDistances(), renderExit(), renderExplosion(), renderFightingUI(), renderGameOverScreen(), renderHealthBar(), renderHelp(), renderNPC(), renderNPC5(), renderShips(), renderShopMenu(), renderSkybox(), renderStation(), renderTextonball(), renderTitleScreen(), renderWaveTransition(), and renderWayPoints().
Vehicles* SP2::midShip private
Definition at line 368 of file SP2.h.
Referenced by shopUpdates().
vector<Vehicles*> SP2::midVehicles private
Definition at line 358 of file SP2.h.
Referenced by objectsInit().
MS SP2::modelStack private
Definition at line 383 of file SP2.h.
Referenced by ballquest(), Render(), renderAsteroid(), renderBullets(), renderchildtext(), renderDistances(), renderExplosion(), renderHealthBar(), RenderMesh(), renderNPC(), renderNPC5(), RenderOnScreen(), renderShips(), renderSkybox(), renderStation(), RenderText(), renderTextonball(), RenderTextOnScreen(), renderTitleScreen(), and renderWayPoints().
Object SP2::NPC5 private
Definition at line 347 of file SP2.h.
Referenced by abductionquest(), npcInit(), NPCUpdates(), renderchildtext(), and renderNPC5().
float SP2::objSize private
Definition at line 328 of file SP2.h.
Referenced by renderExit(), renderFightingUI(), renderGameOverScreen(), renderHelp(), renderShopMenu(), renderTitleScreen(), renderWaveTransition(), shopInit(), and shopUpdates().
MousePicker SP2::picker private
Definition at line 342 of file SP2.h.
Referenced by MouseSelection(), and RTSUpdates().
bool SP2::pickup private
Definition at line 313 of file SP2.h.
Referenced by ballquest(), Init(), and quests().
Vehicles* SP2::place private
Definition at line 374 of file SP2.h.
Referenced by Init(), MouseSelection(), renderShips(), and RTSUpdates().
int SP2::placeType private
Definition at line 375 of file SP2.h.
Referenced by Init(), MouseSelection(), renderShips(), and RTSUpdates().
PlayerVehicle SP2::playerShip private
Definition at line 366 of file SP2.h.
Referenced by asteroidHitboxCheck(), generalUpdates(), inPlayerShipUpdates(), inSpaceStationUpdates(), objectsInit(), playerBulletCreation(), renderDistances(), renderFightingUI(), renderShips(), renderShopMenu(), renderSkybox(), RTSUpdates(), shipHitboxCheck(), shopInit(), and waveTransitionUpdate().
Shop* SP2::playerShop private
Definition at line 351 of file SP2.h.
Referenced by Exit(), renderShopMenu(), shopInit(), and shopUpdates().
MS SP2::projectionStack private
Definition at line 383 of file SP2.h.
Referenced by Init(), RenderMesh(), RenderOnScreen(), RenderText(), RenderTextOnScreen(), and RTSUpdates().
float SP2::readyToUse private
Definition at line 322 of file SP2.h.
Referenced by Init(), and Update().
float SP2::screenHeight private
Definition at line 326 of file SP2.h.
Referenced by Init(), renderExit(), renderFightingUI(), renderGameOverScreen(), renderHelp(), RenderOnScreen(), renderShopMenu(), RenderTextOnScreen(), renderTitleScreen(), renderWaveTransition(), shopInit(), shopUpdates(), and Update().
float SP2::screenWidth private
Definition at line 325 of file SP2.h.
Referenced by Init(), renderExit(), renderFightingUI(), renderGameOverScreen(), renderHelp(), RenderOnScreen(), renderShopMenu(), RenderTextOnScreen(), renderTitleScreen(), renderWaveTransition(), shopInit(), shopUpdates(), and Update().
float SP2::second private
Definition at line 322 of file SP2.h.
vector<Vehicles*> SP2::selection private
Definition at line 372 of file SP2.h.
Referenced by MouseSelection(), removeOneSelection(), renderShips(), RTSUpdates(), selectionSetTarget(), and selectionSetWaypoints().
int SP2::shipbought private
Definition at line 318 of file SP2.h.
Referenced by Init(), quests(), and shopUpdates().
irrklang::ISoundEngine* SP2::shootingsfx = irrklang::createIrrKlangDevice() private
Definition at line 295 of file SP2.h.
Referenced by generalUpdates(), Init(), playerBulletCreation(), and shipBulletCreation().
Vector3 SP2::shopLargePos private
Definition at line 327 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
float SP2::shopLargeRot private
Definition at line 330 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
float SP2::shopLargeScale private
Definition at line 329 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
Vector3 SP2::shopMidPos private
Definition at line 327 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
float SP2::shopMidRot private
Definition at line 330 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
float SP2::shopMidScale private
Definition at line 329 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
Vector3 SP2::shopSmallPos private
Definition at line 327 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
float SP2::shopSmallRot private
Definition at line 330 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
float SP2::shopSmallScale private
Definition at line 329 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
SHOPSTATE SP2::shopState private
Definition at line 335 of file SP2.h.
Referenced by renderShopMenu(), shopInit(), and shopUpdates().
Vector3 SP2::shopTarget private
Definition at line 327 of file SP2.h.
Referenced by shopUpdates().
Vehicles* SP2::smallShip private
Definition at line 369 of file SP2.h.
Referenced by shopUpdates().
vector<Vehicles*> SP2::smallVehicles private
Definition at line 356 of file SP2.h.
Referenced by objectsInit().
stack<Vehicles*> SP2::stackLargeVehicles private
Definition at line 363 of file SP2.h.
Referenced by objectsInit().
stack<Vehicles*> SP2::stackMidVehicles private
Definition at line 364 of file SP2.h.
Referenced by objectsInit().
stack<Vehicles*> SP2::stackSmallVehicles private
Definition at line 362 of file SP2.h.
Referenced by objectsInit().
GAMESTATE SP2::state private
Definition at line 337 of file SP2.h.
Referenced by generalUpdates(), Init(), inPlayerShipUpdates(), inSpaceStationUpdates(), mainMenuUpdates(), Render(), renderFightingUI(), RTSUpdates(), shopUpdates(), Update(), and waveTransitionUpdate().
Object SP2::station private
Definition at line 344 of file SP2.h.
Referenced by objectsInit(), renderDistances(), and stationHitboxCheck().
map<int, stack<Vehicles*> > SP2::storedVehicles private
Definition at line 354 of file SP2.h.
Referenced by Exit(), MouseSelection(), objectsInit(), renderFightingUI(), renderShopMenu(), RTSUpdates(), shipHitboxCheck(), shopUpdates(), and stationHitboxCheck().
vector<Asteroid*> SP2::Vasteroid private
Definition at line 380 of file SP2.h.
Referenced by asteroidHitboxCheck(), asteroidUpdate(), Exit(), generateAsteroid(), MouseSelection(), renderAsteroid(), and stationHitboxCheck().
MS SP2::viewStack private
Definition at line 383 of file SP2.h.
Referenced by Render(), RenderMesh(), RenderOnScreen(), RenderText(), and RenderTextOnScreen().
Wave* SP2::waveFunctions private
Definition at line 387 of file SP2.h.
Referenced by asteroidHitboxCheck(), asteroidUpdate(), generalUpdates(), generateAsteroid(), objectsInit(), renderFightingUI(), renderWaveTransition(), stationHitboxCheck(), Update(), and waveTransitionUpdate().
bool SP2::widescreen private
Definition at line 320 of file SP2.h.
Referenced by Init().
vector<AABB> SP2::worldHitbox private
Definition at line 377 of file SP2.h.
Referenced by generalUpdates(), inSpaceStationUpdates(), and WorldHitboxInit().
The documentation for this class was generated from the following files:
Zyzrag/Source/SP2.h
Zyzrag/Source/SP2.cpp