My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateLine (const std::string &meshName, Vector3 init, Vector3 end)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateSquare (const std::string &meshName, Color color, Vector3 init, Vector3 end)
static Mesh * GenerateQuad (const std::string &meshName, Color color, float lengthX, float lengthY)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color, Vector3 min, Vector3 max)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshName, Color color, unsigned numSlices)
static Mesh * GenerateCone (const std::string &meshName, Color color, unsigned numSlices, float height)
static Mesh * GenerateCone2 (const std::string &meshName, Color color, unsigned numSlices, float height, float degree)
static Mesh * GenerateRing (const std::string &meshName, Color color, float innerRadius, unsigned numSlices)
static Mesh * GenerateSphere (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices, bool hemi=false)
static Mesh * GenerateHollowHemiSphere (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices, float thickness)
static Mesh * GenerateTorus (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices, float Radius, float Thickness)
static Mesh * GenerateTorus2 (const std::string &meshName, Color color, unsigned degree, unsigned numSlices, float Radius, float Thickness)
static Mesh * GenerateCyclinder (const std::string &meshName, Color color, unsigned numSlices, float height, bool innerCyclinder=false, float innerRadius=1, float thickness=1)
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
static Mesh * GenerateFloor (const std::string &meshName, Color color, float lengthX, float lengthY)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 15 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 22 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by SP2::Init().
Mesh * MeshBuilder::GenerateCircle (const std::string & meshName, Color color, unsigned numSlices) static
Definition at line 730 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCone (const std::string & meshName, Color color, unsigned numSlices, float height) static
Definition at line 809 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCone2 (const std::string & meshName, Color color, unsigned numSlices, float height, float degree) static
Definition at line 868 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 241 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color, Vector3 min, Vector3 max) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
min - Min vectors of box
max - Max vectors of box
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 630 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), Mesh::vertexBuffer, Vector3::x, Vector3::y, and Vector3::z.
Mesh * MeshBuilder::GenerateCyclinder (const std::string & meshName, Color color, unsigned numSlices, float height, bool innerCyclinder = false, float innerRadius = 1, float thickness = 1) static
Definition at line 1205 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateFloor (const std::string & meshName, Color color, float lengthX, float lengthY) static
Definition at line 1444 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateHollowHemiSphere (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices, float thickness) static
Definition at line 1028 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateLine (const std::string & meshName, Vector3 init, Vector3 end) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 83 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), Mesh::vertexBuffer, Vector3::x, Vector3::y, and Vector3::z.
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 1360 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by SP2::Init().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color, float lengthX, float lengthZ) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 179 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SP2::Init(), and SP2::renderHealthBar().
Mesh * MeshBuilder::GenerateRing (const std::string & meshName, Color color, float innerRadius, unsigned numSlices) static
Definition at line 768 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices, bool hemi = false) static
Definition at line 940 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), and Mesh::vertexBuffer.
Referenced by SP2::Init().
Mesh * MeshBuilder::GenerateSquare (const std::string & meshName, Color color, Vector3 init, Vector3 end) static
Definition at line 113 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Mesh::vertexBuffer, Vector3::x, and Vector3::z.
Referenced by SP2::Render(), and SP2::renderShips().
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 1387 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SP2::Init().
Mesh * MeshBuilder::GenerateTorus (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices, float Radius, float Thickness) static
Definition at line 1071 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateTorus2 (const std::string & meshName, Color color, unsigned degree, unsigned numSlices, float Radius, float Thickness) static
Definition at line 1116 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
The documentation for this class was generated from the following files:
Zyzrag/Source/MeshBuilder.h
Zyzrag/Source/MeshBuilder.cpp