My Application: pathFinding Class Reference
pathFinding Class Reference
#include <pathFinding.h>
Public Member Functions
pathFinding ()
pathFinding (Vector3 location, Vector3 endlocation)
virtual ~pathFinding ()
void resetWayPoints ()
void pathRoute (double dt)
void updateWayPoints (Vector3 endLocation)
void setInitialWayPoints (Vector3 endLocation)
void setCurrentLocation (Vector3 newCurrLocation)
void setInitialWayPoints (Vector3 location, Vector3 view)
void setInitialDirection (Vector3 view)
void setMaxSpeed (float newSpeed)
void setCurrSpeed (float newSpeed)
float getMaxSpeed ()
float getCurrSpeed ()
float distanceBetween2points (Vector3 Point1, Vector3 Point2)
Vector3 getCurrentLocation ()
Vector3 getLastWayPointDirection ()
queue< Vector3 > getwayPoints ()
Private Attributes
float maxSpeed
float currSpeed
queue< Vector3 > wayPoints
Vector3 currentLocation
Vector3 lastWayPointDirection
Detailed Description
Definition at line 26 of file pathFinding.h.
Constructor & Destructor Documentation
pathFinding::pathFinding ()
pathFinding:
Author
Wong Keng Han Ashley:
Date
15 feb 2016:
: Default constructor
Definition at line 33 of file pathFinding.cpp.
pathFinding::pathFinding (Vector3 location, Vector3 endlocation)
: pathFinding
Author
: Wong Keng Han Ashley
Date
: 15 feb 2016
: overloaded constructor that takes in and sets initial location and final location
Definition at line 58 of file pathFinding.cpp.
pathFinding::~pathFinding () virtual
: pathFinding
Author
: Wong Keng Han Ashley
Date
: 15 feb 2016
: default constructor
Definition at line 83 of file pathFinding.cpp.
Member Function Documentation
float pathFinding::distanceBetween2points (Vector3 Point1, Vector3 Point2)
: pathFinding
Author
: Wong Keng Han Ashley
Date
: 15 feb 2016
: checks the distance between 2 vectors
Definition at line 145 of file pathFinding.cpp.
Vector3 pathFinding::getCurrentLocation ()
: getCurrentLocation
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: return current location
Definition at line 312 of file pathFinding.cpp.
float pathFinding::getCurrSpeed ()
: getSpeed
Author
: Wong Keng Han Ashley
Date
: 19 feb 2016
: return speed
Definition at line 452 of file pathFinding.cpp.
Vector3 pathFinding::getLastWayPointDirection ()
: getLastWayPointDirection
Author
: Wong Keng Han Ashley
Date
: 17 feb 2016
: return the direction of the previous waypoint
Definition at line 378 of file pathFinding.cpp.
float pathFinding::getMaxSpeed ()
: getmaxSpeed
Author
: Wong Keng Han Ashley
Date
: 19 feb 2016
: return maxSpeed
Definition at line 476 of file pathFinding.cpp.
queue< Vector3 > pathFinding::getwayPoints ()
: getwayPoints
Author
: Wong Keng Han Ashley
Date
: 17 feb 2016
: returns the vector of way points
Definition at line 356 of file pathFinding.cpp.
void pathFinding::pathRoute (double dt)
: pathFinding
Author
: Wong Keng Han Ashley
Date
: 15 feb 2016
: moves the object towards the waypoint
Definition at line 103 of file pathFinding.cpp.
void pathFinding::resetWayPoints ()
: resetWayPoints
Author
: Wong Keng Han Ashley
Date
: 16 feb 2016
: remove all current waypoints
Definition at line 286 of file pathFinding.cpp.
Referenced by SP2::MouseSelection().
void pathFinding::setCurrentLocation (Vector3 newCurrLocation)
: setCurrentLocation
Author
: Wong Keng Han Ashley
Date
: 19 feb 2016
: return current location
Definition at line 333 of file pathFinding.cpp.
Referenced by SP2::MouseSelection().
void pathFinding::setCurrSpeed (float newSpeed)
: setSpeed
Author
: Wong Keng Han Ashley
Date
: 18 feb 2016
: set the currSpeed of the vehicle
Definition at line 398 of file pathFinding.cpp.
Referenced by SP2::MouseSelection().
void pathFinding::setInitialDirection (Vector3 view)
Definition at line 224 of file pathFinding.cpp.
References lastWayPointDirection.
void pathFinding::setInitialWayPoints (Vector3 endLocation)
: setInitialWayPoints
Author
: Wong Keng Han Ashley
Date
: 15 feb 2016
: setting initial waypoints for the object
Definition at line 168 of file pathFinding.cpp.
void pathFinding::setInitialWayPoints (Vector3 location, Vector3 view)
: overLoaded setInitialWayPoints
Author
: Wong Keng Han Ashley
Date
: 18 feb 2016
: overloaded function for setting way points
Definition at line 214 of file pathFinding.cpp.
References currentLocation, lastWayPointDirection, Vector3::Normalize(), and wayPoints.
void pathFinding::setMaxSpeed (float newSpeed)
: setMaxSpeed
Author
: Wong Keng Han Ashley
Date
: 18 feb 2016
: set the maxSpeed of the vehicle
Definition at line 429 of file pathFinding.cpp.
void pathFinding::updateWayPoints (Vector3 endLocation)
: updateWayPoints
Author
: Wong Keng Han Ashley
Date
: 15 feb 2016
: setting initial waypoints for the object
Definition at line 247 of file pathFinding.cpp.
Field Documentation
Vector3 pathFinding::currentLocation private
Definition at line 65 of file pathFinding.h.
Referenced by setInitialWayPoints().
float pathFinding::currSpeed private
Definition at line 59 of file pathFinding.h.
Vector3 pathFinding::lastWayPointDirection private
Definition at line 66 of file pathFinding.h.
Referenced by setInitialDirection(), and setInitialWayPoints().
float pathFinding::maxSpeed private
Definition at line 58 of file pathFinding.h.
queue<Vector3> pathFinding::wayPoints private
Definition at line 62 of file pathFinding.h.
Referenced by setInitialWayPoints().
The documentation for this class was generated from the following files:
Zyzrag/Source/pathFinding.h
Zyzrag/Source/pathFinding.cpp