My Application: AABB Class Reference
AABB Class Reference
Contains the class AABB hitbox, along with all it's functions.
#include <AABB.h>
Public Member Functions
AABB ()
Default constructor.
AABB (const Vector3 min, const Vector3 max)
Constructor that takes in Vector3 min and max.
AABB (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Constructor that takes it float of min X, Y, Z and max X, Y, Z.
~AABB ()
Destructor.
void Set (const Vector3 min, const Vector3 max)
Sets the AABB's Vector3 min and max.
void Set (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Sets the AABB's Vector3 min and max.
bool AABBtoAABB (const AABB &box, Vector3 &view)
Checks if current AABB is colliding with another AABB.
bool AABBtoAABB (const AABB &box)
Checks if current AABB is colliding with another AABB.
bool AABBtoAABB (const vector< AABB > &box, Vector3 &view)
Checks if current AABB is colliding with a vector of AABBs.
bool RayToAABB (Vector3 rayOrigin, Vector3 ray)
Checks if current AABB is colliding with a ray.
bool PointToAABB (const Vector3 &position)
Checks if current AABB is colliding with a point.
bool withinPlane (Vector3 init, Vector3 end)
Checks if AABB is within the plane.
Vector3 GetMax ()
Get's Vector3 max of class.
Vector3 GetMin ()
Get's Vector3 min of class.
Private Attributes
Vector3 Max
Vector3 Min
Detailed Description
Contains the class AABB hitbox, along with all it's functions.
Definition at line 30 of file AABB.h.
Constructor & Destructor Documentation
AABB::AABB ()
Default constructor.
Definition at line 23 of file AABB.cpp.
AABB::AABB (const Vector3 min, const Vector3 max)
Constructor that takes in Vector3 min and max.
Parameters
min - Gets the Vector3 minimum value
max - Gets the Vector3 maximum value
Definition at line 36 of file AABB.cpp.
AABB::AABB (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Constructor that takes it float of min X, Y, Z and max X, Y, Z.
Parameters
minX - Mininum X coordinates
minY - Mininum Y coordinates
minZ - Mininum Z coordinates
maxX - Maximum X coordinates
maxY - Maximum Y coordinates
maxZ - Maximum Z coordinates
Definition at line 53 of file AABB.cpp.
References Set().
AABB::~AABB ()
Destructor.
Definition at line 64 of file AABB.cpp.
Member Function Documentation
bool AABB::AABBtoAABB (const AABB & box, Vector3 & view)
Checks if current AABB is colliding with another AABB.
Parameters
box - The other AABB class to check with
view - To check which direction the current AABB is heading.
Returns
Returns true if colliding else false.
Definition at line 114 of file AABB.cpp.
References Max, Min, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::inPlayerShipUpdates(), and SP2::stationHitboxCheck().
bool AABB::AABBtoAABB (const AABB & box)
Checks if current AABB is colliding with another AABB.
Parameters
box - The other AABB class to check with
Returns
Returns true if colliding else false.
Definition at line 136 of file AABB.cpp.
References Max, Min, Vector3::x, Vector3::y, and Vector3::z.
bool AABB::AABBtoAABB (const vector< AABB > & box, Vector3 & view)
Checks if current AABB is colliding with a vector of AABBs.
Parameters
box - vector AABB class to check with
view - To check which direction the current AABB is heading.
Returns
Returns true if colliding else false.
Definition at line 159 of file AABB.cpp.
References Max, Min, Vector3::x, Vector3::y, and Vector3::z.
Vector3 AABB::GetMax ()
Get's Vector3 max of class.
Returns
Returns Vector3 max
Definition at line 277 of file AABB.cpp.
References Max.
Referenced by Object::SetHitbox(), and Object::updateHitbox().
Vector3 AABB::GetMin ()
Get's Vector3 min of class.
Returns
Returns Vector3 min
Definition at line 291 of file AABB.cpp.
References Min.
Referenced by Object::SetHitbox(), and Object::updateHitbox().
bool AABB::PointToAABB (const Vector3 & position)
Checks if current AABB is colliding with a point.
Parameters
position - Position of the point
Returns
Returns true if colliding else false.
Definition at line 184 of file AABB.cpp.
References Max, Min, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::abductionquest(), SP2::ballquest(), and SP2::quests().
bool AABB::RayToAABB (Vector3 rayOrigin, Vector3 ray)
Checks if current AABB is colliding with a ray.
Parameters
rayOrigin - Get's the ray origin ray - Get's where the ray ends at
Returns
Returns true if colliding else false.
Definition at line 207 of file AABB.cpp.
References Max, Min, Vector3::Normalize(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::MouseSelection().
void AABB::Set (const Vector3 min, const Vector3 max)
Sets the AABB's Vector3 min and max.
Parameters
min - Gets the Vector3 mininum value
max - Gets the Vector3 maximum value
Definition at line 77 of file AABB.cpp.
References Max, and Min.
Referenced by AABB(), Object::SetHitbox(), Object::SetHitboxSize(), and Object::updateHitbox().
void AABB::Set (float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
Sets the AABB's Vector3 min and max.
Parameters
minX - Mininum X coordinates
minY - Mininum Y coordinates
minZ - Mininum Z coordinates
maxX - Maximum X coordinates
maxY - Maximum Y coordinates
maxZ - Maximum Z coordinates
Definition at line 96 of file AABB.cpp.
References Max, and Min.
bool AABB::withinPlane (Vector3 init, Vector3 end)
Checks if AABB is within the plane.
Parameters
init - Get's the initial starting point of the plane
end - Get's the ending point of the plane
Returns
True if AABB is within the plane
Definition at line 308 of file AABB.cpp.
References Max, Min, swap(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::MouseSelection().
Field Documentation
Vector3 AABB::Max private
Definition at line 33 of file AABB.h.
Referenced by AABBtoAABB(), GetMax(), PointToAABB(), RayToAABB(), Set(), and withinPlane().
Vector3 AABB::Min private
Definition at line 34 of file AABB.h.
Referenced by AABBtoAABB(), GetMin(), PointToAABB(), RayToAABB(), Set(), and withinPlane().
The documentation for this class was generated from the following files:
Zyzrag/Source/AABB.h
Zyzrag/Source/AABB.cpp