My Application: Zyzrag/Source/MeshBuilder.cpp File Reference
MeshBuilder.cpp File Reference
#include "MeshBuilder.h"
#include "Vertex.h"
#include "MyMath.h"
#include <GL\glew.h>
#include <vector>
Functions
float CircleX (float theta)
float CircleZ (float theta)
float SphereX (float phi, float theta)
float SphereY (float phi)
float SphereZ (float phi, float theta)
Function Documentation
float CircleX (float theta)
Definition at line 720 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCone(), MeshBuilder::GenerateCone2(), MeshBuilder::GenerateCyclinder(), MeshBuilder::GenerateRing(), MeshBuilder::GenerateSphere(), and MeshBuilder::GenerateTorus2().
float CircleZ (float theta)
Definition at line 725 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCone(), MeshBuilder::GenerateCone2(), MeshBuilder::GenerateCyclinder(), MeshBuilder::GenerateRing(), MeshBuilder::GenerateSphere(), and MeshBuilder::GenerateTorus2().
float SphereX (float phi, float theta)
Definition at line 927 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHollowHemiSphere(), and MeshBuilder::GenerateSphere().
float SphereY (float phi)
Definition at line 931 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHollowHemiSphere(), and MeshBuilder::GenerateSphere().
float SphereZ (float phi, float theta)
Definition at line 935 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHollowHemiSphere(), and MeshBuilder::GenerateSphere().